- set_fact:
  no_destroy: "{{ lookup('env','INPUT_TERRAFORM_NO_DESTROY') }}"
  destroy_only: "{{ lookup('env','INPUT_TERRAFORM_DESTROY_ONLY') }}"

- name: Run Terraform Destroy
  terraform:
    project_path: "../terraform"
    state: "absent"
    force_init: true
    backend_config:
      region: "us-east-1"
  when: not no_destroy or no_destroy is not defined

- name: Run Terraform Apply
  terraform:
    project_path: "../terraform"
    state: "present"
    force_init: true
    backend_config:
      region: "{{ lookup('env','INPUT_AWS_DEFAULT_REGION') }}"
  register: tf_command
  when: not destroy_only or destroy_only is not defined

- name: Add dynamically created ec2 instances to roles 
  with_subelements: 
    - "{{ tf_command.outputs }}"
    - value
  add_host:
    name: "{{ item[1] }}"
    group: "ssh_honeypot"
  when: not destroy_only or destroy_only is not defined
