- name: Run Terraform Destroy
  terraform:
    project_path: "../terraform"
    state: "absent"
    force_init: true
  when: not no_refresh or no_refresh is not defined

- name: Run Terraform Apply
  terraform:
    project_path: "../terraform"
    state: "present"
    force_init: true
  register: tf_command
  
- name: Add Add dynamically created ec2 instances to roles 
  with_dict: "{{ tf_command.outputs }}"
  add_host:
    name: "{{ item.value.value }}"
    group: "ssh_honeypot"
