- name: Run Terraform Destroy
  terraform:
    project_path: "../terraform"
    state: "absent"
    force_init: true
    backend_config:
      region: "us-east-1"
  when: not no_refresh or no_refresh is not defined

- name: Run Terraform Apply
  terraform:
    project_path: "../terraform"
    state: "present"
    force_init: true
    backend_config:
      region: "us-east-1"
  register: tf_command

- name: Add dynamically created ec2 instances to roles 
  with_subelements: 
    - "{{ tf_command.outputs }}"
    - value
  add_host:
    name: "{{ item[1] }}"
    group: "ssh_honeypot"
