---
- name: Run Terraform
  hosts:
   - "127.0.0.1"
  roles:
  - terraform
  gather_facts: yes

- name: Honeypot servers
  hosts:
   - all
  roles:
   - ssh_honeypot
  become: yes
  become_method: sudo
  strategy: free 
  gather_facts: no 
