name: 'Cycle Honeypots'
description: 'Cycles Honeypot Servers'
inputs:
  ACTION:
    description: '"cycle_honeypots" to cycle honeypots, or "update_threatlists" to update threatlists.'
    required: true
  SSH_PUBLIC_KEY:
    description: 'Raw public key string to deployed to new honeypot servers. Ansible will use this to log into newly created servers.'
    required: false
  SSH_PRIVATE_KEY:
    description: 'Raw private key string to authenticate to new honeypot servers. Ansible will use this to log into newly created servers.'
    required: false
  AWS_ACCESS_KEY_ID:
    description: 'AWS Access Key ID. Terraform will use this to authenticate and provision new honeypot servers.'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Access Key Secret. Terraform will use this to authenticate and provision new honeypot servers.'
    required: true
  AWS_DEFAULT_REGION:
    description: 'Default region for ansible.'
    required: false
    default: us-east-1
  THREATLIST_OUTPUT_S3_BUCKET_NAME:
    description: 'Name of the s3 bucket to output the threatlist data to. Required if ACTION is "uptdate_threatlists."'
    required: false
  THREATLIST_OUTPUT_S3_FILE_NAME:
    description: 'Name of the file to output the threatlist data to. Required if ACTION is "uptdate_threatlists."'
    required: false
  ELASTICSEARCH_HOST:
    description: 'Elasticsearch Host to retrieve honeypot events from.'
    required: false
  ELASTICSEARCH_PORT:
    description: 'Port to use when retrieving events from Elasticsearch.'
    required: false
  ELASTICSEARCH_SCHEME:
    description: 'HTTP or HTTPS.'
    required: false
  ELASTICSEARCH_USER:
    description: 'Username to authenticate to Elasticsearch host with.'
    required: false
  ELASTICSEARCH_PASSWORD:
    description: 'Password to authenticate to Elasticsearch host with.'
    required: false
  THREATLIST_QUERY_LTE:
    description: 'Latest time (in Elastic Query Language) to aggregate results from. Defaults to "now."'
    default: now
    required: false
  THREATLIST_QUERY_GTE:
    description: 'Earliest time (in Elastic Query Language) to aggregate results from. Example: "now-1h."'
    required: false


runs:
  using: 'docker'
  image: "${{ inputs.ACTION }}/Dockerfile"