name: 'Cycle Honeypots'
description: 'Cycles Honeypot Servers'
inputs:
  SSH_PUBLIC_KEY:
    description: 'Raw public key string to deployed to new honeypot servers. Ansible will use this to log into newly created servers.'
    required: true
  SSH_PRIVATE_KEY:
    description: 'Raw private key string to authenticate to new honeypot servers. Ansible will use this to log into newly created servers.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'