# List of deployable regions in AWS
# This is not the list of regions to deploy to
# We need to create terraform providers for all of them each time 
# even if we are not deploying to them in case of TF destroy
aws_all_deployable_regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - ap-northeast-1
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - eu-north-1
  - sa-east-1