---
- name: Add FileBeat repository
  yum_repository:
    name: filebeat-7.x
    description: FileBeat repository for Open Source 7.x packages
    baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install FileBeat
  yum:
    name: 
      - filebeat
    state: latest
    lock_timeout: 60

- name: Configure filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
  vars:
    elastic_host: "{{ lookup('env','INPUT_ELASTICSEARCH_HOST') }}"
    elastic_port: "{{ lookup('env','INPUT_ELASTICSEARCH_PORT') }}"
    elastic_scheme: "{{ lookup('env','INPUT_ELASTICSEARCH_SCHEME') }}"
    elastic_user: "{{ lookup('env','INPUT_ELASTICSEARCH_USER') }}"
    elastic_password: "{{ lookup('env','INPUT_ELASTICSEARCH_PASSWORD') }}"
  notify: restart filebeat
    
- name: Force a restart if configuration has changed
  meta: flush_handlers

- name: Start FileBeat
  systemd:
    name: filebeat
    state: started
    enabled: yes

