---

- name: Install docker via Amazon Linux Extras CLI
  shell: "amazon-linux-extras install docker -y"
  register: docker_install_result
  changed_when: '"already installed and latest version" not in docker_install_result.stdout'

- name: Start docker
  systemd:
    state: started
    name: docker

- name: Enable Docker on boot
  systemd:
    name: docker
    enabled: yes
    masked: no

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    group: docker

- name: Install docker pip package
  pip:
    name: docker

- name: Get systems public_ip
  become: yes
  become_user: ec2-user
  ipify_facts:
  register: public_ip

- name: Spin up a cowrie container
  docker_container:
    name: cowrie_honeypot
    state: started
    restart_policy: always
    image: cowrie/cowrie
    hostname: "{{ public_ip.ansible_facts.ipify_public_ip }}"
    expose: 2222
    published_ports: 22:2222
