---
- name: Add FileBeat repository
  yum_repository:
    name: filebeat-oss-7.x
    description: FileBeat repository for Open Source 7.x packages
    baseurl: https://artifacts.elastic.co/packages/oss-7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes

- name: Install FileBeat
  yum:
    name: 
      - filebeat
    state: latest
    lock_timeout: 60

- name: Copy ILM policy
  copy:
    src: honey-net-ilm-policy.json
    dest: /etc/filebeat/honey-net-ilm-policy.json
    owner: root
    group: root
    mode: 0600
  notify: restart filebeat

- name: Configure filebeat
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600
  notify: restart filebeat

- name: Enable the geoip pipeline on the elastic server
  uri:
    url: "{{ elastic_scheme }}://{{ elastic_host }}:{{ elastic_port }}/_ingest/pipeline/geoip"
    user: "{{ elastic_user }}"
    password: "{{ elastic_password }}"
    method: PUT
    body: "{{ lookup('file','geoip-pipeline.json') }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
  run_once: yes
  delegate_to: '127.0.0.1'

- name: Force a restart if configuration has changed
  meta: flush_handlers

- name: Start FileBeat
  systemd:
    name: filebeat
    state: started
    enabled: yes
