- name: Create a file called '/tmp/honeypot.txt' with the content 'honey_pot'.
  copy: 
    content: "honey_pot\n" 
    dest: /tmp/honeypot.txt

#- name: upgrade all packages
#  yum:
#    name: '*'
#    state: latest
