- name: Create a file called '/tmp/honeypot.txt' with the content 'honey_pot'.
  copy: 
    content: "honey_pot\n" 
    dest: /tmp/honeypot.txt

- name: Update all the things!
  yum:
    name: '*'
    state: latest

# Workaround for bug: https://github.com/ansible/ansible/issues/56583
# In future, will use yum module's `lock_timeout: 60`
- name: Wait until yum is unlocked
  wait_for:
    path: "/var/run/yum.pid"
    state: absent

- name: Install required packages
  yum:
    name: 
      - python-pip
      - firewalld
    state: latest
    # lock_timeout: 60 # Ansible bug: https://github.com/ansible/ansible/issues/56583

- name: Start firewalld
  systemd:
    state: started
    name: firewalld

- name: Open Alternative SSH Port
  firewalld:
    port: "{{ replacement_ssh_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled