- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#Port"
    line: "#Port 22\nPort 22222"
  register: sshd_config_changed
  
- name: Restart sshd, probably
  systemd:
    name: sshd
    state: restarted
  when: sshd_config_changed.changed
