on: 
  [push]
  # schedule:
  #   # Run at 5am UTC, midnight EST
  #   - cron:  '0 5 * * *'

jobs:
  cycle_honeypot_servers:
    runs-on: ubuntu-latest
    name: Cycle All Honeypot Servers
    steps:

    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CHANNEL: '#honey_net'
        USERNAME: Friendly Honey Net Bot
        ICON_EMOJI: ':bee:'
        TEXT: |
          *Cycling Honeypot Servers* :honey_pot: :cyclone:
          Job: _Cycle All Honeypot Servers_
      run: |
        curl -s -X POST --data-urlencode \
          "payload={
            \"channel\": \"$CHANNEL\",
            \"username\": \"$USERNAME\",
            \"text\": \"$TEXT\",
            \"icon_emoji\": \"$ICON_EMOJI\"
          }" \
          $SLACK_WEBHOOK

    - name: honey_net
      uses: sover02/honey_net@master
      with:
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        AWS_S3_TF_STATE_BUCKET: 'honey-net-terraform-key'
        AWS_HONEYPOT_REGIONS: 'us-east-2,us-west-1,us-west-2,ap-northeast-1,ap-northeast-2,ap-southeast-1,ap-southeast-2,ca-central-1,eu-central-1,eu-west-1,eu-west-2,eu-west-3,eu-north-1,sa-east-1'
        HONEYPOT_SERVERS_PER_REGION: 1
        ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
        ELASTICSEARCH_PORT: ${{ secrets.ELASTICSEARCH_PORT }}
        ELASTICSEARCH_SCHEME: ${{ secrets.ELASTICSEARCH_SCHEME }}
        ELASTICSEARCH_USER: ${{ secrets.ELASTICSEARCH_USER }}
        ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
        ELASTICSEARCH_INDEX_PREFIX: 'honey-net'

    - name: Send Slack Notification
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        CHANNEL: '#honey_net'
        USERNAME: Friendly Honey Net Bot
        ICON_EMOJI: ':bee:'
        TEXT: |
          *Honeypot Server Cycle Completed* :honey_pot: :white_check_mark:
          Job: _Cycle All Honeypot Servers_
      run: |
        curl -s -X POST --data-urlencode \
          "payload={
            \"channel\": \"$CHANNEL\",
            \"username\": \"$USERNAME\",
            \"text\": \"$TEXT\",
            \"icon_emoji\": \"$ICON_EMOJI\"
          }" \
          $SLACK_WEBHOOK
