on: #[push]
  schedule: 
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  refresh_threatlists:
    runs-on: ubuntu-latest
    name: Refreshes threatlists every hour
    steps:

    - name: Slack Notify Started
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: honey_net
        SLACK_COLOR: '#3278BD'
        SLACK_MESSAGE: 'Updating Honey Pot Threatlists! :cyclone:'
        SLACK_TITLE: Threatlist Updates Started
        SLACK_USERNAME: Friendly honey_net Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: update_1hr_threatlist
      uses: sover02/honey_net@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        THREATLIST_ELASTICSEARCH_HOST: ${{ secrets.THREATLIST_ELASTICSEARCH_HOST }}
        THREATLIST_ELASTICSEARCH_PORT: ${{ secrets.THREATLIST_ELASTICSEARCH_PORT }}
        THREATLIST_ELASTICSEARCH_SCHEME: ${{ secrets.THREATLIST_ELASTICSEARCH_SCHEME }}
        THREATLIST_ELASTICSEARCH_USER: ${{ secrets.THREATLIST_ELASTICSEARCH_USER }}
        THREATLIST_ELASTICSEARCH_PASSWORD: ${{ secrets.THREATLIST_ELASTICSEARCH_PASSWORD }}
        THREATLIST_OUTPUT_S3_BUCKET_NAME: tf-honey-net-threat-list
        THREATLIST_OUTPUT_S3_FILE_NAME: threatlist_1hr.csv
        THREATLIST_QUERY_LTE: now
        THREATLIST_QUERY_GTE: now-1h
        ACTION: update_threatlists

    - name: update_24hr_threatlist
      uses: sover02/honey_net@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        THREATLIST_ELASTICSEARCH_HOST: ${{ secrets.THREATLIST_ELASTICSEARCH_HOST }}
        THREATLIST_ELASTICSEARCH_PORT: ${{ secrets.THREATLIST_ELASTICSEARCH_PORT }}
        THREATLIST_ELASTICSEARCH_SCHEME: ${{ secrets.THREATLIST_ELASTICSEARCH_SCHEME }}
        THREATLIST_ELASTICSEARCH_USER: ${{ secrets.THREATLIST_ELASTICSEARCH_USER }}
        THREATLIST_ELASTICSEARCH_PASSWORD: ${{ secrets.THREATLIST_ELASTICSEARCH_PASSWORD }}
        THREATLIST_OUTPUT_S3_BUCKET_NAME: tf-honey-net-threat-list
        THREATLIST_OUTPUT_S3_FILE_NAME: threatlist_24hr.csv
        THREATLIST_QUERY_LTE: now
        THREATLIST_QUERY_GTE: now-24h
        ACTION: update_threatlists

    - name: update_30d_threatlist
      uses: sover02/honey_net@master
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
        THREATLIST_ELASTICSEARCH_HOST: ${{ secrets.THREATLIST_ELASTICSEARCH_HOST }}
        THREATLIST_ELASTICSEARCH_PORT: ${{ secrets.THREATLIST_ELASTICSEARCH_PORT }}
        THREATLIST_ELASTICSEARCH_SCHEME: ${{ secrets.THREATLIST_ELASTICSEARCH_SCHEME }}
        THREATLIST_ELASTICSEARCH_USER: ${{ secrets.THREATLIST_ELASTICSEARCH_USER }}
        THREATLIST_ELASTICSEARCH_PASSWORD: ${{ secrets.THREATLIST_ELASTICSEARCH_PASSWORD }}
        THREATLIST_OUTPUT_S3_BUCKET_NAME: tf-honey-net-threat-list
        THREATLIST_OUTPUT_S3_FILE_NAME: threatlist_30d.csv
        THREATLIST_QUERY_LTE: now
        THREATLIST_QUERY_GTE: now-30d
        ACTION: update_threatlists

    - name: Slack Notify Complete
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: honey_net
        SLACK_COLOR: '#3278BD'
        SLACK_MESSAGE: 'Threatlists have been updated! :cyclone:'
        SLACK_TITLE: Threatlist Update Completed
        SLACK_USERNAME: Friendly honey_net Bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
