on: [push]
# schedule: 
#     # Runs every Saturday
#   - cron:  0 0 * * SAT'

jobs:
refresh_threatlists-7-day-sample:
  runs-on: ubuntu-latest
  name: Refreshes threatlists every week
  steps:

  - name: update_7d-sample_threatlist
    uses: sover02/honey_net@master
    with:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      THREATLIST_OUTPUT_S3_BUCKET_NAME: tf-honey-net-threat-list
      THREATLIST_OUTPUT_S3_FILE_NAME: threatlist_7d_weekly_sample.csv 
      THREATLIST_QUERY_LTE: now
      THREATLIST_QUERY_GTE: now-7d
      ACTION: update_threatlists